
EXAMPLES = distributivity exponentiation harness int2ptr primes rot13 structs sums switch

all:
	for example in ${EXAMPLES} ; do \
		make -C $${example} ;    \
        done



clean:
	for example in ${EXAMPLES} ; do     \
		make -C $${example} clean;  \
        done


